version: "3"
services:
  myapp:
    build: .
    image: desafio_spring_primefaces:0.0.1
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8080:8080"


#docker-compose up -d
>>>>>>> feature/gma
